---

- hosts: all
  become: yes
  tasks:
    - name: Install software
      yum:
        name={{ item }}
        state=latest
        enablerepo=epel
      with_items:
        - tree
        - git
        - dstat
        - nmap
        - curl
        - wget
        - vim-enhanced
        - python-pip
        - python-simplejson
        - ansible
        - ansible-lint
        - irssi
        - "@Development tools"

    - name: Install elastic beanstalk cli
      pip:
        name=awsebcli

    - name: Install ecs-cli
      get_url:
        url=https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
        dest=/usr/local/bin/ecs-cli
        mode=0555
